### PR TITLE
WIP: Changes

### PR DESCRIPTION
**Pull request by MarkBennett**
I'm having trouble with the integration test.

Can you take a look and see if you can get it passing?

### CODE REVIEW

**Review by MarkBennett — COMMENTED** [review]
Great work on this @birm! I really like the new checks.

That tool you found works great! Where did you hear about that?

We just need to add a little pause in the check to make sure the server is running. I run into this all the time too. All works after that!

Small nitpick, do you mind renaming that new function to match the others?

**Comment by waiscodes** [comment]
@MarkBennett Thanks Mark. Your suggestion worked, that check is now passing! 

Ah yes, I totally missed that one, I've renamed that function to match the others. 

Everything looks to be working, ready for final review!

**Comment by birm** [comment]
This has to be the strangest PR I've ever been tagged in.

**Comment by MarkBennett** [comment]
> This has to be the strangest PR I've ever been tagged in.

Ha ha, forgot this was public @birm! Sorry for the spam! 😛 

We're doing a talk to introduce new devs (high school and first year university) to code reviews and pull requests. This is the poor PR we're abusing to show simplified examples of good and bad behaviour.

**Pull request closed without merging**
